<?php
// $Id$ 
/**
 * Rename 5.x-1.0 permission "admin google_disaster_location" and 6.x-1.0 permission
 * "edit google_disaster_location" to "administer google_disaster_location".
 */
function google_disaster_location_update_200() {
  $ret = array();
  
  // Fix role permissions to account for the changed names. Setup the replace 
  // array which holds strings both the old and new permissions.
  $replace = array(
    'admin google_disaster_location' => 'administer google_disaster_location',
    'edit google_disaster_location' => 'administer google_disaster_location'
  );

  // Loop over all the changes, performing necessary updates.
  foreach ($replace as $old_permission => $new_permission) {
    $ret[] = update_sql("UPDATE permission SET perm = REPLACE(perm, '$old_permission', '$new_permission')");
    }
  return $ret;
}

function google_disaster_location_uninstall() {
  variable_del('google_disaster_location_height');
  variable_del('google_disaster_location_width');
  variable_del('google_disaster_location_zoom');
  variable_del('google_disaster_location_type');
  variable_del('google_disaster_location_title');
  variable_del('google_disaster_location_body');
  variable_del('google_disaster_location_footer');
  variable_del('google_disaster_location_key');
  variable_del('google_disaster_location_lat');//TODO do not forget to remove if not used
  variable_del('google_disaster_location_lng');//TODO do not forget to remove if not used

  variable_del('google_disaster_location_type_earthquakes');
  variable_del('google_disaster_location_earthquakes_count');
  variable_del('google_disaster_location_earthquakes_count_link');
  variable_del('google_disaster_location_earthquakes_magnitude');
  variable_del('google_disaster_location_earthquakes_feeds');//TODO do not forget to remove
  variable_del('google_disaster_location_earthquakes_block_refresh');
  variable_del('google_disaster_location_earthquakes_filter_by_countries');
  variable_del('google_disaster_location_path_to_earthquakes_data');

  variable_del('google_disaster_location_type_floods');
  variable_del('google_disaster_location_floods_count');
  variable_del('google_disaster_location_floods_count_link');
  variable_del('google_disaster_location_floods_magnitude');
  variable_del('google_disaster_location_floods_feeds');
  variable_del('google_disaster_location_floods_block_refresh');// TODO do not forget to remove
  variable_del('google_disaster_location_floods_filter_by_countries');
  variable_del('google_disaster_location_path_to_floods_data');

  variable_del('google_disaster_location_type_volcanoes');
  variable_del('google_disaster_location_volcanoes_feeds');
  variable_del('google_disaster_location_volcanoes_count');
  variable_del('google_disaster_location_volcanoes_count_link');
  variable_del('google_disaster_location_volcanoes_filter_by_countries');
  variable_del('google_disaster_location_path_to_volcanoes_data');
}
